# Generated by Django 3.0.6 on 2020-11-25 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0004_delete_reminder'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeBaseCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='KnowledgeBaseArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('likes', models.IntegerField(default=0)),
                ('favorite', models.BooleanField(blank=True, default=False, null=True)),
                ('showcase', models.BooleanField(blank=True, default=False, null=True)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('last_update_date', models.DateTimeField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('state', models.CharField(choices=[('DR', 'Draft'), ('PB', 'Published'), ('PR', 'Private'), ('AR', 'Archived')], default='DR', max_length=2)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.KnowledgeBaseCategory')),
                ('related_cards', models.ManyToManyField(blank=True, related_name='kb_article', to='card.Card')),
            ],
        ),
        migrations.CreateModel(
            name='KnowledgeBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('public', models.BooleanField(default=False)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.Organization')),
            ],
        ),
    ]
