# Generated by Django 3.0.6 on 2020-11-25 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_knowledgebase_knowledgebasearticle_knowledgebasecategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgebasearticle',
            name='knowledgebase',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.KnowledgeBase'),
        ),
    ]
