# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-16 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_organization_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='logo',
            field=models.ImageField(blank=True, upload_to=b'logos'),
        ),
    ]
