# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-07-14 10:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_board_mailbox'),
        ('organization', '0003_organization_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='default_board',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='board.Board'),
        ),
    ]
