# Generated by Django 3.0.6 on 2020-11-25 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_knowledgebasearticle_knowledgebase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgebasearticle',
            name='last_update_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='knowledgebasearticle',
            name='published_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
