# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-07-14 11:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_organization_default_board'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
