# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-07-28 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_auto_20180714_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
