# Generated by Django 3.0.6 on 2020-12-12 15:49

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('organization', '0005_knowledgebasecategory_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgebasearticle',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
