# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-10-23 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0007_auto_20180728_1510'),
        ('organization', '0006_organization_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='boards',
            field=models.ManyToManyField(related_name='organization_boards', to='board.Board'),
        ),
    ]
