# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-10-23 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0007_organization_boards'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='included_hours',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='sla_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='sla_response_time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
