# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-08 17:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization', '0008_auto_20181023_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='contacts',
            field=models.ManyToManyField(blank=True, null=True, related_name='organization_contacts', to=settings.AUTH_USER_MODEL),
        ),
    ]
