# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-06 08:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0009_organization_contacts'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailDomain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='organization',
            name='contacts',
            field=models.ManyToManyField(blank=True, related_name='organization_contacts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organization',
            name='email_domains',
            field=models.ManyToManyField(blank=True, related_name='email_domain', to='organization.EmailDomain'),
        ),
    ]
