# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-08 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0010_auto_20190106_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='allow_external_contacts',
            field=models.BooleanField(default=False),
        ),
    ]
