# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-09 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0011_organization_allow_external_contacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='allow_auto_contact_creation',
            field=models.BooleanField(default=False),
        ),
    ]
