# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-22 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0012_organization_allow_auto_contact_creation'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='csat_exclude',
            field=models.BooleanField(default=False),
        ),
    ]
