# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-23 18:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0013_organization_csat_exclude'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ['name']},
        ),
    ]
