# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-07 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_userprofile_is_automation_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='timezone',
            field=models.CharField(default='Europe/Bucharest', max_length=255),
            preserve_default=False,
        ),
    ]
