# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-07-08 07:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_auto_20180407_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_org_admin',
            field=models.BooleanField(default=False),
        ),
    ]
