# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-07-08 09:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0006_userprofile_is_org_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_related_name', to=settings.AUTH_USER_MODEL),
        ),
    ]
