# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-07-08 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0008_auto_20180708_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_operator',
            field=models.BooleanField(default=False),
        ),
    ]
