# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-07 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
