# Generated by Django 3.0.6 on 2020-10-28 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0002_auto_20201027_1831'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
