# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-07-08 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0005_reminder_notified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
