# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-07-09 05:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0006_auto_20180708_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='column',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_column', to='card.Column'),
        ),
    ]
