# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-10-27 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0010_auto_20180909_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='sla_lifetime',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
