# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-10 12:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0013_card_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='tags',
        ),
    ]
