# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-29 17:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0016_auto_20181208_1753'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ['created_time']},
        ),
    ]
