# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-22 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0017_auto_20190129_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='csat',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
