# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-23 18:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0018_card_csat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_board', to='board.Board'),
        ),
    ]
