# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-10 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracker',
            name='action',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
