# Generated by Django 3.0.6 on 2020-10-27 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracker',
            name='time_spent_in_column',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
