# Generated by Django 2.0 on 2019-12-22 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doit', '0002_tracker_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.ContentType'),
        ),
    ]
