# Generated by Django 3.0.6 on 2020-05-30 14:28

import attachment.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateField(auto_now_add=True)),
                ('content', models.FileField(upload_to=attachment.models.get_upload_path)),
                ('name', models.CharField(max_length=255)),
                ('mimetype', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
