# Generated by Django 3.0.6 on 2020-12-11 20:02

import attachment.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_knowledgebasecategory_company'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attachment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KBAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateField(auto_now_add=True)),
                ('content', models.FileField(upload_to=attachment.models.get_upload_path)),
                ('name', models.CharField(max_length=255)),
                ('mimetype', models.CharField(blank=True, max_length=255, null=True)),
                ('kbarticleid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachment_kbarticle', to='organization.KnowledgeBaseArticle')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
