# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-09-09 11:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0010_auto_20180909_1112'),
        ('attachment', '0002_remove_attachment_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='attachment',
            name='object_id',
        ),
        migrations.AddField(
            model_name='attachment',
            name='card',
            field=models.ForeignKey(default=1234, on_delete=django.db.models.deletion.CASCADE, related_name='attachment_card', to='card.Card'),
            preserve_default=False,
        ),
    ]
