# Generated by Django 2.0 on 2019-12-22 09:25

import attachment.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attachment', '0004_attachment_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='content',
            field=models.FileField(upload_to=attachment.models.get_upload_path),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
