# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-08-15 09:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_auto_20171202_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='billable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='minutes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='overtime',
            field=models.BooleanField(default=False),
        ),
    ]
