# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 11:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contact', '0001_initial'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_time', models.DateField(auto_now=True)),
                ('modified_time', models.DateTimeField(auto_now_add=True)),
                ('archived', models.BooleanField(default=False)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('color', models.CharField(blank=True, choices=[(b'c0', b'#ff8'), (b'#70b500', b'#70b500'), (b'#d9b51c', b'#d9b51c'), (b'#ff9f1a', b'#ff9f1a'), (b'#eb5a46', b'#eb5a46'), (b'#c377e0', b'#c377e0'), (b'#055a8c', b'#055a8c'), (b'#4bbf6b', b'#4bbf6b')], default=b'c0', max_length=12)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.Organization')),
                ('contacts', models.ManyToManyField(blank=True, null=True, to='contact.UserProfile')),
            ],
        ),
    ]
