# Generated by Django 3.0.6 on 2020-05-30 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_time', models.DateField(auto_now=True)),
                ('modified_time', models.DateTimeField(auto_now_add=True)),
                ('archived', models.BooleanField(default=False)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('order', models.IntegerField(blank=True, null=True)),
                ('type', models.CharField(choices=[('project_board', 'Project Board'), ('ongoing_board', 'Ongoing Board'), ('sales_board', 'Sales Board')], default='ongoing_board', max_length=128)),
                ('color', models.CharField(blank=True, choices=[('0', 'Choose a color for this Board'), ('CORNSILK', '#fff8dc'), ('HONEYDUE', '#f0fff0'), ('MINTCREAM', '#f5fffa'), ('LAVENDER', '#e6e6fa'), ('LIGHTSTEEL', '#b0c4de'), ('DARNERTAIL', '#74b9ff'), ('CHIGONG', '#d63031'), ('SOOTHING', '#b2bec3'), ('SHY', '#a29bfe')], default='CORNSILK', max_length=12)),
            ],
        ),
    ]
