# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-10 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_board_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
