# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-30 12:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_mailbox', '0005_auto_20160523_2240'),
        ('board', '0004_auto_20160610_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='mailbox',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Mailbox', to='django_mailbox.Mailbox'),
        ),
    ]
