# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-07-14 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0009_auto_20180714_1134'),
        ('board', '0005_board_mailbox'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='columns',
            field=models.ManyToManyField(related_name='board_columns', to='card.Column'),
        ),
    ]
