# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-07-28 15:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_board_columns'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='columns',
        ),
        migrations.AlterField(
            model_name='board',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='board_organization', to='organization.Organization'),
        ),
    ]
