# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-21 09:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0007_auto_20180728_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='contacts',
            field=models.ManyToManyField(blank=True, null=True, related_name='contact', to=settings.AUTH_USER_MODEL),
        ),
    ]
