# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-27 13:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0008_auto_20190121_0933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='contacts',
        ),
    ]
