# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-14 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0009_remove_board_contacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='type',
            field=models.CharField(choices=[(b'project_board', b'Project Board'), (b'ongoing_board', b'Ongoing Board'), (b'sales_board', b'Sales Board')], default=b'ongoing_board', max_length=128),
        ),
        migrations.AlterField(
            model_name='board',
            name='color',
            field=models.CharField(blank=True, choices=[(b'0', b'Choose a color for this Board'), (b'CORNSILK', b'#fff8dc'), (b'HONEYDUE', b'#f0fff0'), (b'MINTCREAM', b'#f5fffa'), (b'LAVENDER', b'#e6e6fa'), (b'LIGHTSTEEL', b'#b0c4de'), (b'DARNERTAIL', b'#74b9ff'), (b'CHIGONG', b'#d63031'), (b'SOOTHING', b'#b2bec3'), (b'SHY', b'#a29bfe')], default=b'0', max_length=12),
        ),
    ]
