# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-23 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0010_auto_20190414_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='color',
            field=models.CharField(blank=True, choices=[(b'0', b'Choose a color for this Board'), (b'CORNSILK', b'#fff8dc'), (b'HONEYDUE', b'#f0fff0'), (b'MINTCREAM', b'#f5fffa'), (b'LAVENDER', b'#e6e6fa'), (b'LIGHTSTEEL', b'#b0c4de'), (b'DARNERTAIL', b'#74b9ff'), (b'CHIGONG', b'#d63031'), (b'SOOTHING', b'#b2bec3'), (b'SHY', b'#a29bfe')], default=b'CORNSILK', max_length=12),
        ),
    ]
