# Generated by Django 2.0 on 2019-12-22 09:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0011_auto_20191123_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='color',
            field=models.CharField(blank=True, choices=[('0', 'Choose a color for this Board'), ('CORNSILK', '#fff8dc'), ('HONEYDUE', '#f0fff0'), ('MINTCREAM', '#f5fffa'), ('LAVENDER', '#e6e6fa'), ('LIGHTSTEEL', '#b0c4de'), ('DARNERTAIL', '#74b9ff'), ('CHIGONG', '#d63031'), ('SOOTHING', '#b2bec3'), ('SHY', '#a29bfe')], default='CORNSILK', max_length=12),
        ),
        migrations.AlterField(
            model_name='board',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='board_organization', to='organization.Organization'),
        ),
        migrations.AlterField(
            model_name='board',
            name='mailbox',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Mailbox', to='django_mailbox.Mailbox'),
        ),
        migrations.AlterField(
            model_name='board',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='board',
            name='type',
            field=models.CharField(choices=[('project_board', 'Project Board'), ('ongoing_board', 'Ongoing Board'), ('sales_board', 'Sales Board')], default='ongoing_board', max_length=128),
        ),
    ]
